version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-apache
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: postgres:17
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: to_do_list
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
